version: '2'

services:

  ca-org1:
    container_name: ca-org1.dealer.com
    image: hyperledger/fabric-ca:$FABRIC_VERSION
    command: sh -c 'fabric-ca-server start -b admin-org1:adminpw'
    environment:
      - FABRIC_CA_HOME=/FABRIC-CA
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_CA_CERTFILE=/FABRIC-CA/ca-config/ca-org1.dealer.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/FABRIC-CA/ca-config/key.pem
    volumes:
      - ./crypto-config/peerOrganizations/dealer.com/ca/:/FABRIC-CA/ca-config
    ports:
      - "7054:7054"

  ca-org2:
    container_name: ca-org2.insurer.com
    image: hyperledger/fabric-ca:$FABRIC_VERSION
    command: sh -c 'fabric-ca-server start -b admin-org2:adminpw'
    environment:
      - FABRIC_CA_HOME=/FABRIC-CA
      - FABRIC_CA_SERVER_CA_NAME=ca-org2
      - FABRIC_CA_SERVER_CA_CERTFILE=/FABRIC-CA/ca-config/ca-org2.insurer.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/FABRIC-CA/ca-config/key.pem
    volumes:
      - ./crypto-config/peerOrganizations/insurer.com/ca/:/FABRIC-CA/ca-config
    ports:
      - "7154:7154"

  ca-org3:
    container_name: ca-org3.registry.com
    image: hyperledger/fabric-ca:$FABRIC_VERSION
    command: sh -c 'fabric-ca-server start -b admin-org3:adminpw'
    environment:
      - FABRIC_CA_HOME=/FABRIC-CA
      - FABRIC_CA_SERVER_CA_NAME=ca-org3
      - FABRIC_CA_SERVER_CA_CERTFILE=/FABRIC-CA/ca-config/ca-org3.registry.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/FABRIC-CA/ca-config/key.pem
    volumes:
      - ./crypto-config/peerOrganizations/registry.com/ca/:/FABRIC-CA/ca-config
    ports:
      - "7254:7254"
