version: '2'

services:

  peer0.insurer.com:
    container_name: peer0.insurer.com
    image: hyperledger/fabric-peer:$IMAGE_VERSION
    command: peer node start
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.insurer.com
      - CORE_LOGGING_PEER=info
      - CORE_CHAINCODE_LOGGING_LEVEL=info
      - CORE_PEER_LOCALMSPID=InsurerMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_ADDRESS=peer0.insurer.com:7351
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_basic
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5986
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/insurer.com/peers/peer0.insurer.com/msp:/etc/hyperledger/msp/peer
      - ./crypto-config/peerOrganizations/insurer.com/users:/etc/hyperledger/msp/users
      - ./artifacts:/etc/hyperledger/configtx
    ports:
      - 7351:7351
      - 7353:7353

  peer1.insurer.com:
    container_name: peer1.insurer.com
    image: hyperledger/fabric-peer:$IMAGE_VERSION
    command: peer node start
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer1.insurer.com
      - CORE_LOGGING_PEER=info
      - CORE_CHAINCODE_LOGGING_LEVEL=info
      - CORE_PEER_LOCALMSPID=InsurerMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_ADDRESS=peer1.insurer.com:7451
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_basic
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5987
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/insurer.com/peers/peer1.insurer.com/msp:/etc/hyperledger/msp/peer
      - ./crypto-config/peerOrganizations/insurer.com/users:/etc/hyperledger/msp/users
      - ./artifacts:/etc/hyperledger/configtx
    ports:
      - 7451:7451
      - 7453:7453

  couchdb0.insurer.com:
    container_name: couchdb0.insurer.com
    image: hyperledger/fabric-couchdb:$IMAGE_VERSION
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 5986:5986

  couchdb1.insurer.com:
    container_name: couchdb1.insurer.com
    image: hyperledger/fabric-couchdb:$IMAGE_VERSION
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 5987:5987
