version: '2'

services:

  orderer0.cttransf.com:
    container_name: orderer0.cttransf.com
    image: hyperledger/fabric-orderer:$IMAGE_VERSION
    command: orderer
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=info
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
    volumes:
      - ./artifacts/:/etc/hyperledger/configtx
      - ./crypto-config/ordererOrganizations/cttransf.com/orderers/orderer0.cttransf.com/:/etc/hyperledger/msp/orderer
      - ./crypto-config/peerOrganizations/dealer.com/peers/peer0.dealer.com/:/etc/hyperledger/msp/peerOrg1
      - ./crypto-config/peerOrganizations/insurer.com/peers/peer0.insurer.com/:/etc/hyperledger/msp/peerOrg2
      - ./crypto-config/peerOrganizations/registry.com/peers/peer0.registry.com/:/etc/hyperledger/msp/peerOrg3
    ports:
      - 7050:7050

  orderer1.cttransf.com:
    container_name: orderer1.cttransf.com
    image: hyperledger/fabric-orderer:$IMAGE_VERSION
    command: orderer
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=info
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
    volumes:
      - ./artifacts/:/etc/hyperledger/configtx
      - ./crypto-config/ordererOrganizations/cttransf.com/orderers/orderer1.cttransf.com/:/etc/hyperledger/msp/orderer
      - ./crypto-config/peerOrganizations/dealer.com/peers/peer0.dealer.com/:/etc/hyperledger/msp/peerOrg1
      - ./crypto-config/peerOrganizations/insurer.com/peers/peer0.insurer.com/:/etc/hyperledger/msp/peerOrg2
      - ./crypto-config/peerOrganizations/registry.com/peers/peer0.registry.com/:/etc/hyperledger/msp/peerOrg3
    ports:
      - 7150:7150

  orderer2.cttransf.com:
    container_name: orderer2.cttransf.com
    image: hyperledger/fabric-orderer:$IMAGE_VERSION
    command: orderer
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=info
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
    volumes:
      - ./artifacts/:/etc/hyperledger/configtx
      - ./crypto-config/ordererOrganizations/cttransf.com/orderers/orderer2.cttransf.com/:/etc/hyperledger/msp/orderer
      - ./crypto-config/peerOrganizations/dealer.com/peers/peer0.dealer.com/:/etc/hyperledger/msp/peerOrg1
      - ./crypto-config/peerOrganizations/insurer.com/peers/peer0.insurer.com/:/etc/hyperledger/msp/peerOrg2
      - ./crypto-config/peerOrganizations/registry.com/peers/peer0.registry.com/:/etc/hyperledger/msp/peerOrg3
    ports:
      - 7250:7250